// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "protocol/zigbee/app/framework/util/tokens.h"

// Token header for the Manufacturing Library CLI plugin.
#include "protocol/zigbee/app/framework/plugin/manufacturing-library-cli/manufacturing-library-cli-tokens.h"

// Token header for the Configuration server plugin.
#include "protocol/zigbee/app/framework/plugin-soc/configuration-server/configuration-server-tokens.h"

// Token header for the Reporting plugin.
#include "protocol/zigbee/app/framework/plugin/reporting/reporting-tokens.h"

// Token header for the IAS Zone Server plugin.
#include "protocol/zigbee/app/framework/plugin/ias-zone-server/ias-zone-server-tokens.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

